spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?createDatabaseIfNotExist=true
    username: test
    password: Str@6naparola1
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    format-sql: true